# Generated by Django 5.1.6 on 2026-01-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
